### ISSUE TITLE
Demo won't run

### ISSUE THREAD

**Issue by mikeLspohn** [AuthorizeNet/inperson-sdk-ios#29]
I'm not sure if this should be here or in the cocoa pods repository, but I'm getting errors trying to run pod try 'authorizenet-sdk' 

Here's the error log:

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/michael/.rvm/gems/ruby-2.1.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]
    RubyGems : 2.4.2
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.2.1
Ruby lib dir : /Users/michael/.rvm/rubies/ruby-2.1.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 105c7dec8bd9c321666d3e760938d0edef9b51fb
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
target 'AuthnetLab', :exclusive => true do
  pod "authorizenet-sdk", :path => "../"
end

target 'AuthnetLabTests', :exclusive => true do
  pod "authorizenet-sdk", :path => "../"
end
```

### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /private/tmp/CocoaPods/Try/authorizenet-sdk/Example/Pods/Manifest.lock
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `initialize'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `open'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `open'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `write_to_disk'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/installer/migrator.rb:66:in `block in migrate_to_0_36'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/installer/migrator.rb:53:in `migrate_to_0_36'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/installer/migrator.rb:16:in `migrate'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:106:in `block in prepare'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:103:in `prepare'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:90:in `install!'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Users/michael/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/Users/michael/.rvm/gems/ruby-2.1.4/bin/pod:23:in `load'
/Users/michael/.rvm/gems/ruby-2.1.4/bin/pod:23:in `<main>'
/Users/michael/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/Users/michael/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by brianmc** [comment]
If you have CocoaPods installed correctly you should just be able to do:

````
$ pod try 'authorizenet-sdk'
````

If you want to incorporate into your own project you just need to add this line to your Podfile:
````
pod 'authorizenet-sdk'
````
